---
- name: Copy the config file template to the controller
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: ~/kubeadm-config.yaml

- name: Initialize the control plane
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - --config
      - kubeadm-config.yaml
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: kubeadm_init

- name: Show the result of what we'll attempt to put in the join command
  ansible.builtin.debug:
    msg: "{{ kubeadm_init.stdout_lines[-2:] | join(' ') | regex_replace('\\\\', '') | regex_replace('\t', '') }}"

- name: Confirm the join command for workers
  ansible.builtin.set_fact:
    join_command: "{{ kubeadm_init.stdout_lines[-2:] | join(' ') | regex_replace('\\\\', '') | regex_replace('\t', '') }}"
    cacheable: true
  ignore_errors: true

- name: Show the join command just in case
  ansible.builtin.debug:
    var: join_command

- name: Set KUBECONFIG globally
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: export KUBECONFIG=/etc/kubernetes/admin.conf

- name: Wait for the kube-api pod to come online
  ansible.builtin.wait_for:
    port: 6443
    sleep: 5

- name: Install the Flannel manifest
  kubernetes.core.k8s:
    apply: true
    kubeconfig: "{{ lookup('ansible.builtin.env', 'KUBECONFIG') }}"
    src: https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    state: present
