---
- name: Install updates
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Check status of /var/run/reboot-required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Is a reboot needed?
  ansible.builtin.debug:
    msg: "Reboot required."
  when: reboot_required.stat.exists
  changed_when: reboot_required.stat.exists
  notify:
    - 'common : Restart the instance'

- name: Install common packages
  ansible.builtin.package:
    name:
      - containerd
      - netcat-traditional
      - python3-kubernetes
    state: latest

- name: Overwrite the default containerd config
  ansible.builtin.copy:
    src: containerd-config.toml
    dest: /etc/containerd/config.toml
  notify:
    - 'common : Restart containerd'

- name: Install K8S repository
  ansible.builtin.deb822_repository:
    enabled: true
    name: kubernetes
    signed_by: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key"
    uris: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/"
    suites: "/"

- name: Install K8S packages
  ansible.builtin.package:
    update_cache: true
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest
  when: distro == "debian"

- name: Hold K8S packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
